name: Documentation and Helm chart

on:
  push:
    branches:
      - master

jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      charts: ${{ steps.filter.outputs.charts }}
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            docs:
              - 'docs/**/*'
            charts:
              - 'charts/ingress-nginx/Chart.yaml'

  docs:
    name: Update Documentation
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.docs == 'true' }}

    steps:

      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: ./.github/actions/mkdocs
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

  chart:
    name: Release Chart
    runs-on: ubuntu-latest
    needs:
      - changes
    if: ${{ needs.changes.outputs.charts == 'true' }}

    steps:

      - name: Checkout master
        uses: actions/checkout@v1

      - name: Setup
        shell: bash
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-rc.2
        env:
          CR_TOKEN: "${{ secrets.PERSONAL_TOKEN }}"
